#!/usr/bin/env bash

set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

PUBLIC_IP="${PUBLIC_IP:-152.32.190.110}"
MODE="${MODE:-staging}"
WEBROOT="${WEBROOT:-/var/www/letsencrypt}"
BACKEND_URL="${BACKEND_URL:-http://127.0.0.1:8080}"
NGINX_SNIPPET="${NGINX_SNIPPET:-/etc/nginx/conf.d/sub2api-ip-direct.conf}"
RELOAD_HOOK="${RELOAD_HOOK:-/etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh}"
INSTALL_NGINX="${INSTALL_NGINX:-}"
FORCE_RENEWAL="${FORCE_RENEWAL:-0}"
ACME_EMAIL="${ACME_EMAIL:-}"
CERTBOT_UNSAFE_NO_EMAIL="${CERTBOT_UNSAFE_NO_EMAIL:-0}"
NGINX_SNIPPET_BACKUP=""
NGINX_SNIPPET_HAD_EXISTING=0

log() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S %z')" "$*"
}

die() {
  echo "错误: $*" >&2
  exit 1
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    die "请使用 root 权限运行，例如: sudo MODE=staging ACME_EMAIL=ops@example.com $0"
  fi
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "缺少命令: $1"
}

certbot_supports_ip() {
  certbot --help all 2>/dev/null | grep -q -- '--ip-address'
}

certbot_supports_profile() {
  certbot --help all 2>/dev/null | grep -q -- '--preferred-profile'
}

validate_config() {
  [[ "${MODE}" == "staging" || "${MODE}" == "production" ]] || die "MODE 只能是 staging 或 production"
  [[ "${PUBLIC_IP}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || die "PUBLIC_IP 目前仅支持 IPv4: ${PUBLIC_IP}"
  if [[ -z "${INSTALL_NGINX}" ]]; then
    if [[ "${MODE}" == "production" ]]; then
      INSTALL_NGINX=1
    else
      INSTALL_NGINX=0
    fi
  fi
  [[ "${INSTALL_NGINX}" == "0" || "${INSTALL_NGINX}" == "1" ]] || die "INSTALL_NGINX 只能是 0 或 1"
  [[ "${FORCE_RENEWAL}" == "0" || "${FORCE_RENEWAL}" == "1" ]] || die "FORCE_RENEWAL 只能是 0 或 1"
  [[ "${CERTBOT_UNSAFE_NO_EMAIL}" == "0" || "${CERTBOT_UNSAFE_NO_EMAIL}" == "1" ]] || die "CERTBOT_UNSAFE_NO_EMAIL 只能是 0 或 1"
  if [[ -z "${ACME_EMAIL}" && "${CERTBOT_UNSAFE_NO_EMAIL}" != "1" ]]; then
    die "请设置 ACME_EMAIL，或显式设置 CERTBOT_UNSAFE_NO_EMAIL=1"
  fi
}

install_reload_hook() {
  local source_hook

  source_hook="${ROOT_DIR}/deploy/certbot-reload-nginx.sh"
  install -d -m 0755 "$(dirname "${RELOAD_HOOK}")"
  if [[ -f "${source_hook}" ]]; then
    install -m 0755 "${source_hook}" "${RELOAD_HOOK}"
    return
  fi

  cat >"${RELOAD_HOOK}" <<'EOF'
#!/bin/sh

set -eu

nginx -t 2>&1
systemctl reload nginx
EOF
  chmod 0755 "${RELOAD_HOOK}"
}

issue_certificate() {
  local cert_name
  local -a certbot_args email_args renewal_args

  cert_name="${PUBLIC_IP}"
  certbot_args=()
  if [[ "${MODE}" == "staging" ]]; then
    cert_name="${PUBLIC_IP}-staging"
    certbot_args+=(--staging)
  fi

  email_args=()
  if [[ -n "${ACME_EMAIL}" ]]; then
    email_args=(-m "${ACME_EMAIL}")
  else
    email_args=(--register-unsafely-without-email)
  fi

  renewal_args=()
  if [[ "${FORCE_RENEWAL}" == "1" ]]; then
    renewal_args+=(--force-renewal)
  fi

  log "签发 ${MODE} IP 证书: ${PUBLIC_IP} (cert-name=${cert_name})"
  certbot certonly \
    "${certbot_args[@]}" \
    --non-interactive \
    --agree-tos \
    "${email_args[@]}" \
    --preferred-profile shortlived \
    --webroot \
    --webroot-path "${WEBROOT}" \
    --ip-address "${PUBLIC_IP}" \
    --cert-name "${cert_name}" \
    --deploy-hook "${RELOAD_HOOK}" \
    "${renewal_args[@]}"
}

write_nginx_snippet() {
  install -d -m 0755 "$(dirname "${NGINX_SNIPPET}")"
  if [[ -f "${NGINX_SNIPPET}" ]]; then
    NGINX_SNIPPET_HAD_EXISTING=1
    NGINX_SNIPPET_BACKUP="${NGINX_SNIPPET}.$(date +%Y%m%d-%H%M%S).bak"
    cp -a "${NGINX_SNIPPET}" "${NGINX_SNIPPET_BACKUP}"
  fi

  cat >"${NGINX_SNIPPET}" <<EOF
# Optional my4g IP SAN certificate entry for ccSwitch / API-client gray rollout.
# Generated by deploy/setup-my4g-ip-direct.sh.
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    ssl_certificate /etc/letsencrypt/live/${PUBLIC_IP}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${PUBLIC_IP}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 64m;
    underscores_in_headers on;

    location / {
        proxy_pass ${BACKEND_URL};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 1800s;
        proxy_send_timeout 1800s;
    }
}
EOF
}

restore_nginx_snippet() {
  if [[ "${NGINX_SNIPPET_HAD_EXISTING}" == "1" && -n "${NGINX_SNIPPET_BACKUP}" && -f "${NGINX_SNIPPET_BACKUP}" ]]; then
    mv "${NGINX_SNIPPET_BACKUP}" "${NGINX_SNIPPET}"
  else
    rm -f "${NGINX_SNIPPET}"
  fi
}

test_and_reload_nginx() {
  if ! nginx -t; then
    restore_nginx_snippet
    nginx -t >/dev/null 2>&1 || true
    die "Nginx 配置校验失败，已回滚 ${NGINX_SNIPPET}"
  fi
  systemctl reload nginx
}

enable_certbot_timer() {
  if systemctl list-unit-files certbot.timer >/dev/null 2>&1; then
    systemctl enable --now certbot.timer
  else
    log "未找到 certbot.timer，请确认已配置每天至少一次的 certbot renew 任务。"
  fi
}

main() {
  require_root
  validate_config
  for command in certbot grep install nginx systemctl; do
    require_command "${command}"
  done
  certbot_supports_ip || die "当前 certbot 不支持 --ip-address，请升级到 5.4 或更高版本"
  certbot_supports_profile || die "当前 certbot 不支持 --preferred-profile，请升级 certbot"

  install -d -m 0755 "${WEBROOT}"
  install_reload_hook
  issue_certificate

  if [[ "${INSTALL_NGINX}" == "1" ]]; then
    if [[ "${MODE}" != "production" ]]; then
      die "默认只在 production 证书签发后安装 Nginx 入口；如需强制安装请先执行 production 签发"
    fi
    write_nginx_snippet
    test_and_reload_nginx
    enable_certbot_timer
    log "IP 直连入口已启用: https://${PUBLIC_IP}"
  else
    log "staging 证书签发流程已完成。正式启用请执行: sudo MODE=production ACME_EMAIL=${ACME_EMAIL:-ops@example.com} ${0}"
  fi
}

main "$@"
